{% set name = "eurostat" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/eurostat-{{ version }}.tar.gz
  sha256: 6b70c5278084f603d6e92f481c1893f8ccc96f80d09347a822873a7ee679d54d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - pandas
    - requests

test:
  imports:
    - eurostat
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/eurostat/
  summary: Eurostat Python Package
  dev_url: https://bitbucket.org/noemicazzaniga/eurostat/src/master/
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - julian-belina
